[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.7.6"
optimizer = true
optimizer_runs = 200
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@ganache/=node_modules/@ganache/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@truffle/=node_modules/@truffle/",
    "hardhat/=node_modules/hardhat/",
    "truffle/=node_modules/truffle/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
